\trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "Agent is ready on $(Agent.OS)"
  displayName: 'Check agent readiness'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- script: |
    echo "Listing target folder contents:"
    ls -R $(System.DefaultWorkingDirectory)/target || echo "No target folder found"
  displayName: 'Check target folder'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target/*.jar'
    ArtifactName: 'drop'
