trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# 👇 Step 1: Build with Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

# 👇 Step 2: Debug — check what was built
- script: |
    echo "Listing target folder contents:"
    ls -R $(System.DefaultWorkingDirectory)/target || echo "No target folder found"
  displayName: 'Check target folder'

# 👇 Step 3: Publish the WAR file as an artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target/helloworld.war'
    ArtifactName: 'drop'
    publishLocation: 'Container'
